require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DefaultAvatarsController do

  # This should return the minimal set of attributes required to create a valid
  # DefaultAvatar. As you add validations to DefaultAvatar, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefaultAvatarsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all default_avatars as @default_avatars" do
      default_avatar = DefaultAvatar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:default_avatars).should eq([default_avatar])
    end
  end

  describe "GET show" do
    it "assigns the requested default_avatar as @default_avatar" do
      default_avatar = DefaultAvatar.create! valid_attributes
      get :show, {:id => default_avatar.to_param}, valid_session
      assigns(:default_avatar).should eq(default_avatar)
    end
  end

  describe "GET new" do
    it "assigns a new default_avatar as @default_avatar" do
      get :new, {}, valid_session
      assigns(:default_avatar).should be_a_new(DefaultAvatar)
    end
  end

  describe "GET edit" do
    it "assigns the requested default_avatar as @default_avatar" do
      default_avatar = DefaultAvatar.create! valid_attributes
      get :edit, {:id => default_avatar.to_param}, valid_session
      assigns(:default_avatar).should eq(default_avatar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DefaultAvatar" do
        expect {
          post :create, {:default_avatar => valid_attributes}, valid_session
        }.to change(DefaultAvatar, :count).by(1)
      end

      it "assigns a newly created default_avatar as @default_avatar" do
        post :create, {:default_avatar => valid_attributes}, valid_session
        assigns(:default_avatar).should be_a(DefaultAvatar)
        assigns(:default_avatar).should be_persisted
      end

      it "redirects to the created default_avatar" do
        post :create, {:default_avatar => valid_attributes}, valid_session
        response.should redirect_to(DefaultAvatar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved default_avatar as @default_avatar" do
        # Trigger the behavior that occurs when invalid params are submitted
        DefaultAvatar.any_instance.stub(:save).and_return(false)
        post :create, {:default_avatar => {}}, valid_session
        assigns(:default_avatar).should be_a_new(DefaultAvatar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DefaultAvatar.any_instance.stub(:save).and_return(false)
        post :create, {:default_avatar => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested default_avatar" do
        default_avatar = DefaultAvatar.create! valid_attributes
        # Assuming there are no other default_avatars in the database, this
        # specifies that the DefaultAvatar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DefaultAvatar.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => default_avatar.to_param, :default_avatar => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested default_avatar as @default_avatar" do
        default_avatar = DefaultAvatar.create! valid_attributes
        put :update, {:id => default_avatar.to_param, :default_avatar => valid_attributes}, valid_session
        assigns(:default_avatar).should eq(default_avatar)
      end

      it "redirects to the default_avatar" do
        default_avatar = DefaultAvatar.create! valid_attributes
        put :update, {:id => default_avatar.to_param, :default_avatar => valid_attributes}, valid_session
        response.should redirect_to(default_avatar)
      end
    end

    describe "with invalid params" do
      it "assigns the default_avatar as @default_avatar" do
        default_avatar = DefaultAvatar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DefaultAvatar.any_instance.stub(:save).and_return(false)
        put :update, {:id => default_avatar.to_param, :default_avatar => {}}, valid_session
        assigns(:default_avatar).should eq(default_avatar)
      end

      it "re-renders the 'edit' template" do
        default_avatar = DefaultAvatar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DefaultAvatar.any_instance.stub(:save).and_return(false)
        put :update, {:id => default_avatar.to_param, :default_avatar => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested default_avatar" do
      default_avatar = DefaultAvatar.create! valid_attributes
      expect {
        delete :destroy, {:id => default_avatar.to_param}, valid_session
      }.to change(DefaultAvatar, :count).by(-1)
    end

    it "redirects to the default_avatars list" do
      default_avatar = DefaultAvatar.create! valid_attributes
      delete :destroy, {:id => default_avatar.to_param}, valid_session
      response.should redirect_to(default_avatars_url)
    end
  end

end
